version: '3.8'
services:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    ports:
      - "9090:9090"
    links:
      - blackbox_exporter
      - alertmanager
    volumes:
      - "./config:/etc/prometheus"
      - "./data/prometheus:/prometheus"
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.18.0
    ports:
      - "9115:9115"
    dns: 8.8.8.8
    restart: always
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml

  alertmanager:
    image: prom/alertmanager:v0.21.0
    restart: always
    links:
      - alertlogger
    ports:
      - "9093:9093"
    volumes:
      - "./data/alertmanager:/data"
      - "./config:/etc/alertmanager"
    command: --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/data

  flakyhost.com:
    environment:
      - HITS_FAIL_COUNT=30
    build: flakyhost
    restart: always
    ports:
      - "9567:80"

  reliablehost.com:
    environment:
      - HITS_FAIL_COUNT=0
    build: flakyhost
    restart: always
    ports:
      - "9568:80"

  alertlogger:
    build: alertlogger
    restart: always
    ports:
      - "9566:8088"
    environment:
      - LOG_ALERT_PATH=/data/alerts.log
    volumes:
      - "./data/alertlogger:/data"
