global:
  resolve_timeout: 5m 
route:
  receiver: 'default-receiver'
  group_wait: 1s
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - send_resolved: true
        url: http://alertlogger:8088/
