global:
  evaluation_interval: 10s
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/prometheus.rules.yaml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]
    file_sd_configs:
      - files: ['/etc/prometheus/blackbox_targets.yml']
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox_exporter:9115
